### ISSUE TITLE
OBI would like to take on the SCDO "catheter" term

### ISSUE THREAD

**Issue by ddooley** [scdodev/scdo-ontology#16]
Is that ok?

Your http://purl.obolibrary.org/obo/SCDO_0000190 term has definition:"A flexible, tubular device that is used to carry fluids into or from a blood vessel, hollow organ, or body cavity."

OBI proposes to generalize this a bit: "A device which is a flexible tube inserted into a body and which enables transfer of fluids into or out of a body."

**Comment by scdodev** [comment]
Hi. We are reusing this term from MESH, but if you incorporate it with the broader definition and let us know, we can point to your term instead.

**Comment by ddooley** [comment]
The OBI catheter term has now been merged into draft obi-edit.owl via devices.owl.  The term's ID is: OBI:0002830

**Comment by scdodev** [comment]
Have now updated our Catheter term to point to and have the broader definition of the OBI term OBI:0002830.
