### ISSUE TITLE
Remaining merge artifacts in Makefile and scdo-edit.owl

### ISSUE THREAD

**Issue by althonos** [scdodev/scdo-ontology#6]
Hi!

I tried building the latest version of the SCDO with the usual `make` pipeline, but it can't be built currently because of unresolved git merges in `Makefile` and `scdo-edit.owl`, e.g.:
```xml
    <Declaration>
<<<<<<< HEAD
=======
        <AnnotationProperty IRI="http://scdontology.h3abionet.org/ontology/SCDO_1000347"/>
    </Declaration>
    <Declaration>
        <AnnotationProperty IRI="http://scdontology.h3abionet.org/ontology/SCDO_1000380"/>
    </Declaration>
    <Declaration>
>>>>>>> new-repo
        <AnnotationProperty IRI="http://www.geneontology.org/formats/oboInOwl#created_by"/>
    </Declaration>
```

Are you still using the release pipeline or building the ontology directly from an external tool (e.g. Protege) ATM?

**Comment by scdodev** [comment]
Closing this as this should be fixed in the new release.
