### ISSUE TITLE
Add license to ontology and README.md

### ISSUE THREAD

**Issue by matentzn** [scdodev/scdo-ontology#9]
Admission to OBO requires an open license;

in your OWL file, you have a license property, but not related to anything.

I can help you implementing this, but you need to chose between:
http://creativecommons.org/licenses/by/4.0/
http://creativecommons.org/publicdomain/zero/1.0/

Unless you have already decided.
part of review for https://github.com/OBOFoundry/OBOFoundry.github.io/issues/392

**Comment by scdodev** [comment]
@matentzn 

We have these properties specified in the owl file:
dc:license --> GPL-3.0
dc:LicenseDocument --> https://www.gnu.org/licenses/gpl-3.0.en.html

Not acceptable?

**Comment by matentzn** [comment]
I cannot find the GPL in the current version, but this here would be the right way to do it for OBO in owlxml:

https://github.com/INCATools/ontology-development-kit/blob/master/docs/License.md#owlxml-example

Is there any particular reason you chose GPL3 over CC-0 or CC-BY?

**Comment by cthoyt** [comment]
@scdodev @JadeHotchkiss checking in on this - GPL3 is not appropriate for data, further, it doesn't conform to the the OBO Foundry's openness principle https://obofoundry.org/principles/fp-001-open.html which states ontologies should have CC-0 or CC-BY licenses. The purpose of this requirement is to ensure that OBO Foundry ontologies can freely be integrated within each other without licensing issues, and more broadly, so OBO Foundry ontologies can be used by downstream users unencumbered. Again, GPL3 is appropriate for code, but not data, so this could cause some issues. It would be great if you could switch to one of CC-0 or CC-BY licenses.

**Comment by scdodev** [comment]
Will be changing our license to CC-BY in our next release, as follows:
<terms:license rdf:resource="http://creativecommons.org/licenses/by/4.0/"/>

**Comment by scdodev** [comment]
Will also add reference to updated license in README.md file with new release
